version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:3.7.0
    networks:
      - franz
    volumes:
      - zookeeper:/bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
      ZOO_CLIENT_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_LOG_LEVEL: ERROR
    healthcheck:
      # https://issues.apache.org/jira/browse/ZOOKEEPER-2116
      test: zkCli.sh -server localhost:2181 ls "/"
      interval: 5s
      timeout: 10s
      retries: 10

  kafka:
    image: bitnami/kafka:2.8.1
    networks:
      - franz
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 29092:29092
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.3
    networks:
      - franz
    depends_on:
      - kafka
    ports:
      - 28081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: full_transitive
      SCHEMA_REGISTRY_DEBUG: "true"
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: DEBUG

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - franz
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 28080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

networks:
  franz:
    name: franz

volumes:
  zookeeper:
  kafka:
